matrix:
  include:
    - language: java
      jdk: openjdk11
      dist: xenial
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
      services:
        - docker
      before_install:
        - docker pull amazon/dynamodb-local
        - docker run -d -p 8000:8000 amazon/dynamodb-local
        - docker ps
        - chmod +x gradlew
      script:
        - ./gradlew clean build
      after_success:
        - bash <(curl -s https://codecov.io/bash)
      deploy:
        - provider: s3
          access_key_id: $ACCESS_KEY_ID
          secret_access_key: $SECRET_ACCESS_KEY
          region: $REGION
          bucket: $FUNCTIONS_BUCKET
          skip_cleanup: true
          local_dir: cots-match/build/distributions
        - provider: s3
          access_key_id: $ACCESS_KEY_ID
          secret_access_key: $SECRET_ACCESS_KEY
          region: $REGION
          bucket: $FUNCTIONS_BUCKET
          skip_cleanup: true
          local_dir: cots-player/build/distributions
    - language: node_js
      node_js: 13.9.0
      dist: xenial
      before_install:
        - cd cots-web
      install:
        - npm install
      script:
        - npm run build
      deploy:
        - provider: s3
          access_key_id: $ACCESS_KEY_ID
          secret_access_key: $SECRET_ACCESS_KEY
          region: $REGION
          bucket: $WEB_BUCKET
          skip_cleanup: true
          local_dir: cots-web/build

deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY_ID
    secret_access_key: $SECRET_ACCESS_KEY
    region: $REGION
    bucket: $AWS_BUCKET
    skip_cleanup: true
    local_dir: cots-aws
#  - provider: cloudformation
#    access_key_id: $ACCESS_KEY_ID
#    secret_access_key: $SECRET_ACCESS_KEY
#    region: $REGION
#    template: https://cots-aws.s3-ap-southeast-2.amazonaws.com/cots-cloudformation-template.yml
#    stack_name: cots
